---
# This playbook deploys the whole application stack in this site modified to test jenkins.


- name: configure and install the webservers and deploy application code
  hosts: awsServers
  roles:
    - webdeploy
  tags: deploy

- name: undeploy files and shutdown webservers
  hosts: awsServers
  roles:
    - webundeploy
  tags: undeploy
